added miskos edits

diff --git a/usr/bin/lite-tweaks b/usr/bin/lite-tweaks
--- a/usr/bin/lite-tweaks
+++ b/usr/bin/lite-tweaks
@@ -11,45 +11,45 @@
 # Set functions for non-root execution
 # The ones that need root go to the other file: lite-software-super
 FIREFOX() {
-	echo "#Removing the Firefox cache..."
-  			rm -rf $HOME/.cache/mozilla/
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    echo "#Removing the Firefox cache..."
+              rm -rf $HOME/.cache/mozilla/
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error"
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nRemoving the Firefox cache!"
                         fi
 }
 
 CHROME() {
-	echo "#Removing the Google Chrome cache..."
-			rm -rf $HOME/.cache/google-chrome/ 
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    echo "#Removing the Google Chrome cache..."
+            rm -rf $HOME/.cache/google-chrome/ 
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error"
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nRemoving the Google Chrome cache!"
                         fi
 }
 
 CHROMIUM() {
-	echo"#Removing the Chromium cache..."
-			rm -rf $HOME/.cache/chromium/
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    echo"#Removing the Chromium cache..."
+            rm -rf $HOME/.cache/chromium/
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error"
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nRemoving the Chromium cache!"
                         fi
 }
 
 THUMBNAILS() {
-	echo "#Deleting Thumbnail Cache..."
-	sleep 1
-			 rm -rf $HOME/.thumbnails/*
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    echo "#Deleting Thumbnail Cache..."
+    sleep 1
+             rm -rf $HOME/.thumbnails/*
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error"
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nDeleting Thumbnail Cache!"
                         fi
@@ -60,9 +60,9 @@ echo "#Cleaning Whisker Menu Recently Used items..."
 sleep 1
  sed -i 's/^recent=.*$/recent=/g' ~/.config/xfce4/panel/whiskermenu-1.rc 
 
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error"
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nCleaning Whisker Menu Recently Used items!"
                         fi
@@ -72,15 +72,39 @@ sleep 2
 }
 
 TRASH() {
-	echo "#Emptying the Trash bin..."
-	sleep 1
- 			 rm -rf $HOME/.local/share/Trash/files/*
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    echo "#Emptying the Trash bin..."
+    sleep 1
+              rm -rf $HOME/.local/share/Trash/files/*
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error"
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nEmptying the Trash bin!"
                         fi
+}
+
+DU() {
+DU_TEXT="Double click on any <b>Partition</b> to open in the file manager.
+Click on any Column to sort the information."
+DU_TITLE="Disk Usage"
+TMP_DU=$(mktemp /tmp/diskusage.XXXXX)
+
+df -h -T| tail -n+2 | while read fs type size used rest target; do
+    if [[ $rest ]] ; then
+        echo ${fs} ${type} ${size}B ${used}B ${rest}B ${target} |grep /dev/sd |
+    awk '{print $1,"\n",$2,"\n",$3,"\n",$4,"\n",$5,"\n",$6}BEGIN{ s = 7; e = 35; }{for (i=s; i<=e; i++) printf("%s%s", $(i), i<e ? OFS : "\n"); }' #Workaround for disk labels that contain whitespaces(number of characters that can be divided by whitespace =e-s)
+    fi
+done |sed -e 's/[ \t]*$//' $1|  tee $TMP_DU 
+
+SEL=$(cat $TMP_DU | zenity --list --width=600 --height=350 --title="${DU_TITLE}" --text="${DU_TEXT}" --column="Device" --column="Filesystem" --column="Size" --column="Used" --column="Free" --column="%Used" --column="Partition" --print-column="7" "${DFARRAY[@]}")
+
+if [ -z "$SEL" ]; then
+rm -f $TMP_DU
+return
+fi
+
+thunar "$SEL"
+rm -f $TMP_DU
 }
 
 # Set the dialogue window icon
@@ -115,6 +139,11 @@ fi
 echo $selection | grep "Chromium" > /dev/null
 if [ $? = 0 ];then
 ARRAYA+=('CHROMIUM')
+fi
+
+echo $selection | grep "Display Disk Usage" > /dev/null
+if [ $? = 0 ];then
+ARRAYA+=('DU')
 fi
 
 echo $selection | grep "Thumbnail Cache" > /dev/null
@@ -157,6 +186,10 @@ if [ $? = 0 ];then
 ARRAYB+=('RESIDCONFIG')
 fi
 
+echo $selection | grep "Bootup Fix" > /dev/null
+if [ $? = 0 ];then
+ARRAYB+=('FIXBOOTUP')
+fi
 }
 
 RUN() {
@@ -164,118 +197,130 @@ RUN() {
 # If it is skip the execution
 if [ ${#ARRAYA[@]} -ne 0 ]; then
 
-	x=0
-	for k in "${!ARRAYA[@]}"; do  x=$(( $x + 1 )); done  # Get the total number of selected items in array A
+    x=0
+    for k in "${!ARRAYA[@]}"; do  x=$(( $x + 1 )); done  # Get the total number of selected items in array A
 
-	TOTAL_LINES=$x
+    TOTAL_LINES=$x
 
-	printf '%s \n' "${ARRAYA[@]}"|
-	while read  line
-		do
-			eval $line     # Execute functions one by one
-			if [ $? = 1 ]; then
-				zenity --error --title="Lite Tweaks" --text="There was an error while performing cleaning:\n ${line}"
-				exit 1
-			fi	
-		let i++
-		 (( PERCENTAGE = 100 \* ${i} / ${TOTAL_LINES} ))
-		 echo "$PERCENTAGE"
+    printf '%s \n' "${ARRAYA[@]}"|
+    while read  line
+        do
+            $line     # Execute functions one by one
+            if [ $? = 1 ]; then
+                zenity --error --title="Lite Tweaks" --text="There was an error while performing cleaning:\n ${line}"
+                exit 1
+            fi    
+        let i++
+         (( PERCENTAGE = 100 \* ${i} / ${TOTAL_LINES} ))
+         echo "$PERCENTAGE"
 
-		if [ "$PERCENTAGE" == "100" ]; then
-			echo "#Done"
-			sleep 2
-		fi
-	
-	done| zenity --progress  --title="Lite Tweaks" --auto-kill --auto-close --width=300
+        if [ "$PERCENTAGE" == "100" ]; then
+            echo "#Done"
+            sleep 2
+        fi
+    
+    done| zenity --progress  --title="Lite Tweaks" --auto-kill --auto-close --width=300
 fi
 
 # Check if ARRAYB is empty
 # If it is skip the execution
 if [ ${#ARRAYB[@]} -ne 0 ]; then
-	gksudo /usr/bin/lite-tweaks-super "${ARRAYB[@]}"      # Open the next file with superuser privileges and pass the array B
+    gksudo /usr/bin/lite-tweaks-super "${ARRAYB[@]}"      # Open the next file with superuser privileges and pass the array B
 fi
 
-zenity --info --title="Lite Tweaks" --text="Process(s) complete."
+if zenity --question --title="Lite Tweaks" --text="Process(s) complete.\nWould you like to continue using Lite-Tweaks?"; then
+    return
+else
+    exit 0
+fi
 }
 
 CHECK() {
 # Check package cache exists
 if [ "$(find /var/cache/apt/archives/ -maxdepth 1 -size +100k)" ];  then
-	APTCACHESIZE=$(du -sh /var/cache/apt/archives/ | awk '{print $1}' | sed 's/$/B/')
-	aptcache=(FALSE "Package Cache" "Clean" "Packages" "Safe" "You can currently remove $APTCACHESIZE worth of files from your package cache" )
+    APTCACHESIZE=$(du -sh /var/cache/apt/archives/ | awk '{print $1}' | sed 's/$/B/')
+    aptcache=(FALSE "Package Cache" "Clean" "Packages" "Safe" "You can currently remove $APTCACHESIZE worth of files from your package cache" )
 else
-	aptcache=(FALSE "Package Cache" "Clean" "Packages" "Safe" "You can currently remove 0kB worth of files from your package cache")
+    aptcache=(FALSE "Package Cache" "Clean" "Packages" "Safe" "You can currently remove 0kB worth of files from your package cache")
 fi
 
 # Check if archived /var/log files exist
 if [ "$(find /var/log -type f \( -iname \*.gz -o -iname \*.0 -o -iname \*.1 \) -maxdepth 100 -size +1k)" ];  then
-	LOGARCHIVESIZE=$(find /var/log -type f \( -iname \*.gz -o -iname \*.0 -o -iname \*.1 \) -exec du -csh '{}' + | tail -1 | awk '{print $1}' | sed 's/$/B/')
-	logarchive=(FALSE "Log Archives" "Clean" "System" "Safe" "You can currently remove $LOGARCHIVESIZE worth of archived logs" )
+    LOGARCHIVESIZE=$(find /var/log -type f \( -iname \*.gz -o -iname \*.0 -o -iname \*.1 \) -exec du -csh '{}' + | tail -1 | awk '{print $1}' | sed 's/$/B/')
+    logarchive=(FALSE "Log Archives" "Clean" "System" "Safe" "You can currently remove $LOGARCHIVESIZE worth of archived logs" )
 else
-	logarchive=(FALSE "Log Archives" "Clean" "System" "Safe" "You can currently remove 0kB worth of archived logs")
+    logarchive=(FALSE "Log Archives" "Clean" "System" "Safe" "You can currently remove 0kB worth of archived logs")
 fi
 
 # Check if firefox cache exists
 if [  -d  "$HOME/.cache/mozilla/" ];then
-	FFCACHESIZE=$(du -sh "$HOME/.cache/mozilla/"| awk '{print $1}'| sed 's/$/B/')
-	firefox=("FALSE"  "Firefox" "Clean" "Internet" "Safe" "You can currently remove $FFCACHESIZE from your Firefox cache" )
+    FFCACHESIZE=$(du -sh "$HOME/.cache/mozilla/"| awk '{print $1}'| sed 's/$/B/')
+    firefox=("FALSE"  "Firefox" "Clean" "Internet" "Safe" "You can currently remove $FFCACHESIZE from your Firefox cache" )
 else
         firefox=()
 fi
 
 # Check if the google-chrome cache exists
 if [ -d  "$HOME/.cache/google-chrome/" ]; then
-	GCCACHESIZE=$(du -sh $HOME/.cache/google-chrome/ | awk '{print $1}' | sed 's/$/B/')
-	chrome=("FALSE" "Chrome" "Clean" "Internet" "Safe" "You can currently remove $GCCACHESIZE from your Chrome cache" )
-	else
+    GCCACHESIZE=$(du -sh $HOME/.cache/google-chrome/ | awk '{print $1}' | sed 's/$/B/')
+    chrome=("FALSE" "Chrome" "Clean" "Internet" "Safe" "You can currently remove $GCCACHESIZE from your Chrome cache" )
+    else
         chrome=() 
 fi
 
 # Check if the chromium cache exists
 if [  -d  "$HOME/.cache/chromium/" ]; then
-	CHRCACHESIZE=$(du -sh $HOME/.cache/chromium/ | awk '{print $1}' | sed 's/$/B/')
-	chromium=("FALSE" "Chromium" "Clean" "Internet" "Safe" "You can currently remove $CHRCACHESIZE from your Chromium cache" )
+    CHRCACHESIZE=$(du -sh $HOME/.cache/chromium/ | awk '{print $1}' | sed 's/$/B/')
+    chromium=("FALSE" "Chromium" "Clean" "Internet" "Safe" "You can currently remove $CHRCACHESIZE from your Chromium cache" )
 else
          chromium=() # Main zenity dialogue window
 fi
 
-# Check if there are any residual configuration files - to be fixed in the future, currently reporting incorrectly
-# if [ $(dpkg-query -f '${Package} ${Status}\n' -W | grep config-files$ | cut -d" " -f1)  ]; then
-#        RESCONFIGQTY=$(dpkg-query -f '${Package} ${Status}\n' -W | grep config-files$ | cut -d" " -f1 | sed 's/,/ /g'| wc -w)
-#	resconfig=("FALSE" "Residual Config Files" "Clean" "Packages" "Safe" "You currently have $RESCONFIGQTY residual configuration files you can remove" )
-# else
-#        resconfig=("FALSE" "Residual Config Files" "Clean" "Packages" "Safe" "There are no residual configuration files that can be removed" ) 
-# fi
+# Check if there are any residual configuration files
+if [ ! -z  "$(dpkg -l | grep '^rc')"  ]; then
+        RESCONFIGQTY=$(dpkg -l | grep '^rc' | awk '{print $2}'| wc -w)
+    resconfig=(FALSE "Residual Config Files" "Clean" "Packages" "Safe" "You currently have $RESCONFIGQTY residual configuration files you can remove" )
+else
+        resconfig=( FALSE "Residual Config Files" "Clean" "Packages" "Safe" "There are no residual configuration files that can be removed" ) 
+fi
 
 # Check if any thumbnails exist
 if [ $(du -sk $HOME/.thumbnails/ | awk '{print $1}')  -gt 100  ]; then
         THUMBCACHESIZE=$(du -sh $HOME/.thumbnails/ | awk '{print $1}' | sed 's/$/B/')
-	thumbn=("FALSE" "Thumbnail Cache" "Clean" "Images" "Safe" "You can currently remove $THUMBCACHESIZE from your thumbnail cache" )
+    thumbn=("FALSE" "Thumbnail Cache" "Clean" "Images" "Safe" "You can currently remove $THUMBCACHESIZE from your thumbnail cache" )
 else
         thumbn=( "FALSE" "Thumbnail Cache" "Clean" "Images" "Safe" "You can currently remove 0kB from your thumbnail cache" ) 
 fi
 
 # Check if Whisker Menu has Recently Used items
 if [ -z "$(cat $HOME/.config/xfce4/panel/whiskermenu-1.rc | grep "^recent=" | cut -d '=' -f2)" ]; then
-	whisker_recent=(FALSE "Whisker Menu" "Clean" "Menu" "Safe" "Whisker Menu has no Recently Used items to clean" )
+    whisker_recent=(FALSE "Whisker Menu" "Clean" "Menu" "Safe" "Whisker Menu has no Recently Used items to clean" )
 else
-	whisker_test=$(cat $HOME/.config/xfce4/panel/whiskermenu-1.rc | grep "^recent=" | cut -d '=' -f2 | sed 's/,/ /g'| wc -w)
-	whisker_recent=(FALSE "Whisker Menu" "Clean" "Menu" "Safe" "You can currently remove $whisker_test Recently Used items from your Whisker Menu" )
+    whisker_test=$(cat $HOME/.config/xfce4/panel/whiskermenu-1.rc | grep "^recent=" | cut -d '=' -f2 | sed 's/,/ /g'| wc -w)
+    whisker_recent=(FALSE "Whisker Menu" "Clean" "Menu" "Safe" "You can currently remove $whisker_test Recently Used items from your Whisker Menu" )
 fi
 
 # Check if the Trash is empty
 if [  "$(ls -A $HOME/.local/share/Trash/files/)" ]; then
         TRASHCACHESIZE=$(du -sh $HOME/.local/share/Trash/ | awk '{print $1}' | sed 's/$/B/')
-	trash=("FALSE" "Trash Bin" "Clean" "Home" "Safe" "You can currently remove $TRASHCACHESIZE from your Trash bin" )
+    trash=("FALSE" "Trash Bin" "Clean" "Home" "Safe" "You can currently remove $TRASHCACHESIZE from your Trash bin" )
 else
         trash=() 
 fi
+
+# Check LL version
+LL_VERSION=$(awk '{print $3}' /etc/llver)
+case $LL_VERSION in
+2.0)fixbootup=() ;;
+2.2)fixbootup=(FALSE "Bootup Fix" "Fix" "Repair" "Safe" "Fix the bootup" ) ;;
+2.4)fixbootup=() ;;
+esac
 }
 
 #Main loop
 while (true); do
 
-CHECK		# first run the checks
+CHECK        # first run the checks
 
 # Main zenity dialogue window
 selection=$(zenity --window-icon="$ic" --list --checklist --width=880 --height=500 --column="Select" --column="Name" --column="Task" --column="Category" --column="Status" \
@@ -284,12 +329,14 @@ FALSE "Autoremove Packages" "Clean" "Packages" "Safe" "Remove packages installed
 "${chrome[@]}" \
 "${chromium[@]}" \
 FALSE "Default Web Browser" "Preferred" "Browser" "Safe" "Set your default web browser" \
+FALSE "Display Disk Usage" "Information" "System" "safe" "Display overall disk usage information" \
 "${firefox[@]}" \
+"${fixbootup[@]}" \
 FALSE "Kernel Removal" "Clean" "System" "Caution" "Remove kernels you no longer wish to boot from" \
 FALSE "Locate Large Files" "Information" "System" "Caution" "Find files on your system within a size range" \
 "${logarchive[@]}" \
 "${aptcache[@]}" \
-FALSE "Residual Config Files" "Clean" "Packages" "Safe" "Remove residual configuration files from your system" \
+"${resconfig[@]}" \
 "${thumbn[@]}" \
 "${trash[@]}" \
 "${whisker_recent[@]}" )
diff --git a/usr/bin/lite-tweaks-super b/usr/bin/lite-tweaks-super
--- a/usr/bin/lite-tweaks-super
+++ b/usr/bin/lite-tweaks-super
@@ -47,13 +47,18 @@ if [ $? = 0 ];then
 ARRAYC+=('RCONFIG')
 fi
 
+echo $FRM | grep "FIXBOOTUP" > /dev/null
+if [ $? = 0 ];then
+ARRAYC+=('FIXBOOTUP')
+fi
+
 CLEAN() {
 echo "#Cleaning the package cache..."
 sleep 2
-	sudo apt-get clean
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    sudo apt-get clean
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error..."
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nCleaning the package cache!"
                         fi
@@ -62,34 +67,34 @@ sleep 2
 LARCHIVES() {
 echo "#Deleting archived logs..."
 sleep 2
-	sudo find /var/log \( -name '*.gz' -o -name '*.0' -o -name '*.1' \) -exec rm -rf {} \;
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    sudo find /var/log \( -name '*.gz' -o -name '*.0' -o -name '*.1' \) -exec rm -rf {} \;
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error..."
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nDeleting archived logs!"
                         fi
 }
 
 REMOVE() {
-	echo "#Removing unneeded packages..."
-	sleep 2
-			sudo apt-get autoremove -y 
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    echo "#Removing unneeded packages..."
+    sleep 2
+            sudo apt-get autoremove -y 
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error..."
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nRemoving unneeded packages!"
                         fi
 }
 
 RCONFIG() {
-	echo "#Removing residual configuration files..."
-	sleep 1
-			sudo dpkg --purge `dpkg --get-selections | grep deinstall | cut -f1` 
-			if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+    echo "#Removing residual configuration files..."
+    sleep 1
+            sudo dpkg --purge `dpkg -l | grep '^rc' | awk '{print $2}'` 
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                         echo "#Error..."
-					sleep 2
+                    sleep 2
                                         zenity --error \
                                         --title="Error" --text="There was an error while\nRemoving residual configuration files!"
                         fi
@@ -107,74 +112,74 @@ test_4=(` grep "x-scheme-handler/https" $file`)
 
 hash firefox 2>/dev/null
 if [ "${PIPESTATUS[0]}" -eq "0"  ]; then
-	if [ "${test_1[0]}" = "application/xhtml+xml=firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=firefox.desktop;" ]; then
-        	firefox=("TRUE" "Firefox" "default" "Firefox is currently your default web browser" )
-	else
-		firefox=("FALSE" "Firefox" "not default" "Set firefox as the default web browser" )
-	fi
+    if [ "${test_1[0]}" = "application/xhtml+xml=firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=firefox.desktop;" ]; then
+            firefox=("TRUE" "Firefox" "default" "Firefox is currently your default web browser" )
+    else
+        firefox=("FALSE" "Firefox" "not default" "Set firefox as the default web browser" )
+    fi
 else 
-	firefox=()
+    firefox=()
 fi
 
 hash chromium-browser 2>/dev/null
 if [ "${PIPESTATUS[0]}" -eq "0"  ]; then
-	if [ "${test_1[0]}" = "application/xhtml+xml=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=chromium-browser.desktop;firefox.desktop;" ]; then
-		chromium=("TRUE" "Chromium" "default" "Chromium is currently your default web browser" )
-	else
-		chromium=("FALSE" "Chromium" "not default" "Set Chromium as the default web browser" )
-	fi
+    if [ "${test_1[0]}" = "application/xhtml+xml=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=chromium-browser.desktop;firefox.desktop;" ]; then
+        chromium=("TRUE" "Chromium" "default" "Chromium is currently your default web browser" )
+    else
+        chromium=("FALSE" "Chromium" "not default" "Set Chromium as the default web browser" )
+    fi
 else
-	chromium=()
+    chromium=()
 fi
 
 hash midori 2>/dev/null
 if [ "${PIPESTATUS[0]}" -eq "0"  ]; then
-	if [ "${test_1[0]}" = "application/xhtml+xml=midori.desktop;firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=midori.desktop;firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=midori.desktop;firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=midori.desktop;firefox.desktop;" ]; then
-		midori=("TRUE" "Midori" "default" "Midori is currently your default web browser" )
-	else
-		midori=("FALSE" "Midori" "not default" "Set Midori as the default web browser" )
-	fi
+    if [ "${test_1[0]}" = "application/xhtml+xml=midori.desktop;firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=midori.desktop;firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=midori.desktop;firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=midori.desktop;firefox.desktop;" ]; then
+        midori=("TRUE" "Midori" "default" "Midori is currently your default web browser" )
+    else
+        midori=("FALSE" "Midori" "not default" "Set Midori as the default web browser" )
+    fi
 else
-	midori=()
+    midori=()
 fi
 
 hash google-chrome 2>/dev/null
 if [ "${PIPESTATUS[0]}" -eq "0"  ]; then
-	if [ "${test_1[0]}" = "application/xhtml+xml=google-chrome.desktop;firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=google-chrome.desktop;firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=google-chrome.desktop;firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=google-chrome.desktop;firefox.desktop;" ]; then
-		googlechrome=("TRUE" "Google Chrome" "default" "Google Chrome is currently your default web browser" )
-	else
-		googlechrome=("FALSE" "Google Chrome" "not default" "Set Google Chrome as the default web browser" )
-	fi
+    if [ "${test_1[0]}" = "application/xhtml+xml=google-chrome.desktop;firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=google-chrome.desktop;firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=google-chrome.desktop;firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=google-chrome.desktop;firefox.desktop;" ]; then
+        googlechrome=("TRUE" "Google Chrome" "default" "Google Chrome is currently your default web browser" )
+    else
+        googlechrome=("FALSE" "Google Chrome" "not default" "Set Google Chrome as the default web browser" )
+    fi
 else
-	googlechrome=()
+    googlechrome=()
 fi
 
-		selection=$(zenity --window-icon="$ic" --list --radiolist --width=650 --height=200 --column="Select" --column="Name" --column="Status" \
-		--column="Description" --text="Select the web browser you wish to set as default." --title="Choose default browser" --ok-label="Set" --cancel-label="Cancel" \
-		"${firefox[@]}" "${googlechrome[@]}" "${chromium[@]}" "${midori[@]}" )
-		
-		# "The kill switch"
-		 if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-			return
-		fi
-	case "$selection" in
-	"Firefox") `sed -i "s!^"${test_1[0]}"!application/xhtml+xml=firefox.desktop;!g" /etc/gnome/defaults.list `;
-		   `sed -i "s!^"${test_2[0]}"!text/html=firefox.desktop;!g" /etc/gnome/defaults.list `; \
-		   `sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=firefox.desktop;!g" /etc/gnome/defaults.list `; \
-		   `sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=firefox.desktop;!g" /etc/gnome/defaults.list `;;
-	"Google Chrome") `sed -i "s!^"${test_1[0]}"!application/xhtml+xml=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_2[0]}"!text/html=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
-	"Chromium") `sed -i "s!^"${test_1[0]}"!application/xhtml+xml=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_2[0]}"!text/html=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
-	"Midori") `sed -i "s!^"${test_1[0]}"!application/xhtml+xml=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_2[0]}"!text/html=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
-	   `sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
-	esac
+        selection=$(zenity --window-icon="$ic" --list --radiolist --width=650 --height=200 --column="Select" --column="Name" --column="Status" \
+        --column="Description" --text="Select the web browser you wish to set as default." --title="Choose default browser" --ok-label="Set" --cancel-label="Cancel" \
+        "${firefox[@]}" "${googlechrome[@]}" "${chromium[@]}" "${midori[@]}" )
+        
+        # "The kill switch"
+         if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+            return
+        fi
+    case "$selection" in
+    "Firefox") `sed -i "s!^"${test_1[0]}"!application/xhtml+xml=firefox.desktop;!g" /etc/gnome/defaults.list `;
+           `sed -i "s!^"${test_2[0]}"!text/html=firefox.desktop;!g" /etc/gnome/defaults.list `; \
+           `sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=firefox.desktop;!g" /etc/gnome/defaults.list `; \
+           `sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=firefox.desktop;!g" /etc/gnome/defaults.list `;;
+    "Google Chrome") `sed -i "s!^"${test_1[0]}"!application/xhtml+xml=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_2[0]}"!text/html=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
+    "Chromium") `sed -i "s!^"${test_1[0]}"!application/xhtml+xml=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_2[0]}"!text/html=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
+    "Midori") `sed -i "s!^"${test_1[0]}"!application/xhtml+xml=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_2[0]}"!text/html=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
+       `sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
+    esac
 unset file
 }
 
@@ -317,35 +322,48 @@ zenity --question --title="$APPNAME"  --text="Do you want to proceed? You are ab
 
 PROCEED=$(zenity --info --title="$APPNAME" --window-icon=/usr/share/icons/zenity-llcc.png --width=270 --text="The cleaner has finished."; echo $?)
 if [ ${PROCEED} -eq 1 ]; then
-	zenity --info --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="$APPNAME Complete."
-	return
+    zenity --info --title="$APPNAME" --window-icon="${INSTALL_ICON}" --text="$APPNAME Complete."
+    return
 else
-	return
+    return
 fi
 }
 
-	x=0
-	for k in "${!ARRAYC[@]}"; do  x=$(( $x + 1 )); done  # Get the total number of selected items in the array
+FIXBOOTUP() {
+    echo "#Fixing the bootup..."
+sudo sed -i "s/Ubuntu 14.04/Linux Lite 2.2/;s/black=0x2c001e/black=0x000000/;s/white=0xffffff/white=0xffffff/;s/brown=0xff4012/brown=0xffff00/;s/blue=0x988592/blue=0x000000/" /lib/plymouth/themes/ubuntu-text/ubuntu-text.plymouth && sudo update-initramfs -u
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nFixing the bootup!"
+                        fi
+echo 'Linux Lite 2.2 LTS \n \l' | sudo tee /etc/issue
+sudo sed -i 's/^DISTRIB_DESCRIPTION=.*$/DISTRIB_DESCRIPTION=Linux Lite 2.2/g' /etc/lsb-release
+}
 
-	TOTAL_LINES=$x
+    x=0
+    for k in "${!ARRAYC[@]}"; do  x=$(( $x + 1 )); done  # Get the total number of selected items in the array
 
-	printf '%s \n' "${ARRAYC[@]}"|
-	while read  line
-		do
-			eval $line     # Execute functions one by one
-			if [ $? = 1 ]; then
-				zenity --info --title="Lite Tweak" --text="Error:\n${line}"
-			fi	
-		let i++
-		 (( PERCENTAGE = 100 \* ${i} / ${TOTAL_LINES} ))
-		 echo "$PERCENTAGE"
+    TOTAL_LINES=$x
 
-		if [ "$PERCENTAGE" == "100" ]; then
-			echo "#Done"
-			sleep 2
-		fi
-	
-	done| zenity --progress  --title="Lite Tweaks" --auto-kill --auto-close --width=300 --no-cancel
+    printf '%s \n' "${ARRAYC[@]}"|
+    while read  line
+        do
+            $line     # Execute functions one by one
+            if [ $? = 1 ]; then
+                zenity --info --title="Lite Tweak" --text="Error:\n${line}"
+            fi    
+        let i++
+         (( PERCENTAGE = 100 \* ${i} / ${TOTAL_LINES} ))
+         echo "$PERCENTAGE"
+
+        if [ "$PERCENTAGE" == "100" ]; then
+            echo "#Done"
+            sleep 2
+        fi
+    
+    done| zenity --progress  --title="Lite Tweaks" --auto-kill --auto-close --width=300 --no-cancel
 
 unset ARAYC
 unset FRM
